### ISSUE TITLE
Images rendered blurry in fzf preview.

### ISSUE THREAD

**Issue by yrammos** [hzeller/timg#102]
When `timg` is used as image viewer for `fzf` previews, images appear blurry in Kitty without the `-p kitty` parameter.

*With* the aforementioned parameter, previews do not work at all: a string of characters is instead dumped.

Command passed to fzf:

`timg -p kitty -E --frames=1 --loops=1 -g $(( $COLUMNS / 2 - 4 ))x$(( $FZF_PREVIEW_LINES * 2 )) "$1"`

**Comment by hzeller** [comment]
With 'blurry' you mean that it outputs it as block graphics ?

I suspect fzf filters out the non-standard escape codes that are used to send the image to kitty. Applications that provide an terminal app do that often to prevent munging the UI elements.

There is nothing timg can do here, you need to ask the fzf project if it is possible to allow certain image output extension like the kitty protocol.

**Comment by yrammos** [comment]
Makes sense — thank you, @hzeller.
