### ISSUE TITLE
No package 'libdeflate' found

### ISSUE THREAD

**Issue by mhous33** [hzeller/timg#107]
I am running Ubuntu 20.04 with all dependencies installed. I have no issues building version 1.4.5, however cannot build new 1.5.x versions with the new libdeflate dependency, even though I have libdeflate-dev, libdeflate-tools, and libdeflate0 installed:

`(base) mhous33@mhous33-IdeaPad-3-15ALC6:~/Downloads/timg-1.5.1/build$ apt search libdeflate
Sorting... Done
Full Text Search... Done
libdeflate-dev/focal,now 1.5-3 amd64 [installed]
  headers for whole-buffer compression and decompression library

libdeflate-tools/focal,now 1.5-3 amd64 [installed]
  tools for whole-buffer compression and decompression library

libdeflate0/focal,now 1.5-3 amd64 [installed,automatic]
  fast, whole-buffer DEFLATE-based compression and decompression

(base) mhous33@mhous33-IdeaPad-3-15ALC6:~/Downloads/timg-1.5.1/build$ cmake ../
-- The CXX compiler identification is GNU 9.4.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Found Git: /usr/bin/git (found version "2.25.1") 
-- Checking for module 'libdeflate'
--   No package 'libdeflate' found
CMake Error at /home/mhous33/miniconda3/share/cmake-3.22/Modules/FindPkgConfig.cmake:603 (message):
  A required package was not found
Call Stack (most recent call first):
  /home/mhous33/miniconda3/share/cmake-3.22/Modules/FindPkgConfig.cmake:825 (_pkg_check_modules_internal)
  CMakeLists.txt:34 (pkg_check_modules)

-- Configuring incomplete, errors occurred!
See also "/home/mhous33/Downloads/timg-1.5.1/build/CMakeFiles/CMakeOutput.log".
(base) mhous33@mhous33-IdeaPad-3-15ALC6:~/Downloads/timg-1.5.1/build$`

BTW, nice to see an AppImage! Have been creating my own until now, since timg is not available in 20.04 repos.

*EDIT*
The version of libdeflate on Ubuntu 20.04 is 1.5-3, and does not work.
I compiled and installed the latest version from [source](https://github.com/ebiggers/libdeflate)
and am now able to compile this.

**Comment by hzeller** [comment]
In #109, I've now added a fallback to find the library if there is no pkg-config-findable one, and changed the CI to test this on Ubuntu 20.04.
So this should make it possible for you to compile on your system.
