### ISSUE TITLE
ipv4 vs. ipv6

### ISSUE THREAD

**Issue by Combowombo** [hzeller/timg#108]
is there a way to  force use ipv4? there must be some bug in my archlinux that's defaulting to ipv6 and its making my connections time out. Or, which service does timg use to pull the image from a url?

**Comment by hzeller** [comment]
Image loading from an URL is delegated to ImageMagick inside `timg`, so I don't really know an answer to that question. Maybe ImageMagick needs to be compiled with IPv6 support ?

**Comment by hzeller** [comment]
If ImageMagick can't read the URL, maybe using the video subsystem can help, it also has URL support built-in usually

You can tell timg to just use the video subsystem using the `-V` option (of course, it needs to be compiled in, but if you use the default cmake settings, it is included)

```
timg -V https://....
```

**Comment by hzeller** [comment]
Did it work ?

**Comment by Combowombo** [comment]
i don't think it worked or it may be missing something. i might try a different solution or go without images. Thanks though!
