### ISSUE TITLE
Snap packaging for timg

### ISSUE THREAD

**Issue by simos** [hzeller/timg#12]
Snaps are installation packages than can work across different distributions.

I attach the configuration file for a snap for timg.
[timg-snap.zip](https://github.com/hzeller/timg/files/797957/timg-snap.zip)

I also uploaded the timg snap in the "beta" channel of the Ubuntu Store.
It can be installed (in Ubuntu and other distributions that have snap packages enabled) with

`snap install --channel=beta timg`

I enabled the _strict confinement_ for the snap. This means that it can only render images that are located in the home directory of the user.

**Comment by hzeller** [comment]
Thanks @simos 
I guess we can close this old issue now.
Snap package maintained by Simos and available on https://snapcraft.io/timg
