### ISSUE TITLE
Opensllde Error

### ISSUE THREAD

**Issue by JasonGrace2282** [hzeller/timg#127]
`timg` keeps crashing with the following error
```bash
$ timg --version 
timg: error while loading shared libraries: libopenslide.so.0: cannot open shared object file: No such file or directory
```

How I installed:
```bash
$ paru -S timg
```
OS: Arch Linux

**Comment by hzeller** [comment]
Can you ask the maintainer of the Arch package to fix it ? Sounds like a missing dependency.

**Comment by JasonGrace2282** [comment]
Do you happen to know which dependency?

**Comment by hzeller** [comment]
the shared library that is reported missing: openslide.

**Comment by JasonGrace2282** [comment]
Interestingly, even `paru -S openslide python-openslide` don't seem to be able to fix it.

**Comment by hzeller** [comment]
Not much we can do here, I'd ask the packager of the Arch package.

**Comment by JasonGrace2282** [comment]
Can't replicate.
