### ISSUE TITLE
How to concurrently loop videos in a grid?

### ISSUE THREAD

**Issue by korciuch** [hzeller/timg#139]
Currently, I'm using the following command to display a grid of videos playing the first 10 frames; however, it is rendering one-at-a-time.
`timg --grid=5x1 --upscale=i --center --title --frames=1 --threads=8 --loops=1 -wr0 --verbose --clear --compress=1 ~/Downloads/*.mp4`
Is it possible to have the videos play concurrently for faster viewing?

**Comment by hzeller** [comment]
Right now, this is not possible, as each of them is considered a separate entity that starts after the last is shown.
Having said that, that would be a cool feature.
