### ISSUE TITLE
Homebrew Installation

### ISSUE THREAD

**Issue by Miserlou** [hzeller/timg#14]
Great utility! It'd be really nice to be able to install this on OSX using [homebrew](https://brew.sh/)!

**Comment by hzeller** [comment]
Where did you hear about it ? Looks like a bunch of people starred this utility in the last two hours :)

I don't have an Apple machine at hand, but if there are any instructions you'd like to share how to do that, consider sending a pull request for either an documentation update or including the actual scripts.

**Comment by Miserlou** [comment]
You're on the front page of Hacker News!

https://news.ycombinator.com/item?id=13902002

**Comment by hzeller** [comment]
That would explain it :)

**Comment by hzeller** [comment]
See #20, where @mooreniemi describes a brew install.

**Comment by hzeller** [comment]
@speedy-beaver this is what you're working on.

**Comment by speedy-beaver** [comment]
https://github.com/Homebrew/homebrew-core/pull/73770 got merged yesterday and `timg v1.2.1` is now part of homebrew-core 

Please run `brew update` before running `brew install timg`
