### ISSUE TITLE
Undefined reference to symbol 'CloneImageInfo'

### ISSUE THREAD

**Issue by sebelk** [hzeller/timg#15]
Hi,

I can't build, errors are as follows:

```
LANG=C make
g++ -o timg timg.o terminal-canvas.o `GraphicsMagick++-config --ldflags --libs`
/usr/bin/ld: timg.o: undefined reference to symbol 'CloneImageInfo'
/usr/lib64/libGraphicsMagick-Q16.so.3: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:7: recipe for target 'timg' failed
make: *** [timg] Error 1
```

However:
```
readelf -s /usr/lib64/libGraphicsMagick-Q16.so.3| grep -i CloneImageInfo
   544: 00000000000b7120   823 FUNC    GLOBAL DEFAULT   11 CloneImageInfo
```

Packages versions:
```
libwebp-devel-0.5.2-1.fc25.x86_64
GraphicsMagick-1.3.25-6.fc25.x86_64
```

SO is: `Fedora 25`

Thanks in advance

**Comment by hzeller** [comment]
So `timg` never refers to that symbol directly, so it might be an issue with the way `GraphicsMagick++-config` considers which libraries to link and probably misses one ?

If you do a `git pull` for a recent version of `timg` (changed the Makefile), you better see what `GraphicsMagick++-config` expands to, maybe you see a missing library ?

**Comment by sebelk** [comment]
I use the last commit to date commit:

```
git show --shortstat 
commit 95708eaca47c4651545817fc5ccf3cc3346570b2
Author: Henner Zeller <h.zeller@acm.org>
Date:   Sun Mar 19 08:50:01 2017 -0700

    o Better detect failure to determine screen size.

 1 file changed, 7 insertions(+), 7 deletions(-)
```

Output of GraphicsMagick-config:
```GraphicsMagick++-config --ldflags --libs
-lGraphicsMagick++
```
It blames to /usr/lib64/libGraphicsMagick-Q16.so.3, but:

```
rpm -qf /usr/lib64/libGraphicsMagick-Q16.so.3
GraphicsMagick-1.3.25-6.fc25.x86_64
```
Any ideas?

Thanks in advance!

**Comment by hzeller** [comment]
What you want to check is how the output of
`GraphicsMagick++-config --ldflags --libs` looks like.
On debian for instance it is
```
-L/usr/lib -L/usr/lib/X11 -L/usr/lib/x86_64-linux-gnu
-lGraphicsMagick++ -lGraphicsMagick -ljbig -lwebp -llcms2 -ltiff -lfreetype -ljpeg -lpng16 -lwmflite -lXext -lSM -lICE -lX11 -llzma -lbz2 -lxml2 -lz -lm -lgomp -lpthread
```
including all libraries that the graphics magic is depending on. If there is one missing, it might well be that you get a linking error.

If so, this looks like a misconfiguration in the Fedora package, which I suggest to figure out with them.

**Comment by sebelk** [comment]
@hzeller 

Yes, you're right

```
GraphicsMagick++-config --ldflags --libs

-lGraphicsMagick++
```

I've managed to compile with:

`g++ -o timg timg.o terminal-canvas.o  -lGraphicsMagick++ -lGraphicsMagick`

Thanks!

**Comment by grene78** [comment]
adding -lGraphicsMagick solved my very similar issue attempting to compile with VisualGDB on stretch.

**Comment by TragicWarrior** [comment]
Adding -lGraphicsMagick fixed it for me.  Anyone who tries to compile on Fedora 31 is going to run into this.

**Comment by hzeller** [comment]
can you file a bug with them to fix the config output?
