### ISSUE TITLE
Optimization with Terminator

### ISSUE THREAD

**Issue by Vimos** [hzeller/timg#17]
This repo is great! It works well with ubuntu gnome default terminal. 
But I am using Terminator as my terminal, the display is not quite clear. Is there any suggestion that I could optimise the display?

**Comment by hzeller** [comment]
Sometimes, this depends on the font you are using, sometimes terminals add fine lines between the characters which might change with different font-sizes. Can you try to increase/decrease font-size and see if this changes things ?

**Comment by hzeller** [comment]
Last year, the [environment variable `TIMG_USE_UPPER_BLOCK`](https://github.com/hzeller/timg#choice-of-rendering-block) was added to work around quirks in some font rendering. Maybe this is what could prevent the issue ? (though it is years later now, the terminal probably is working fine now :) ).
