### ISSUE TITLE
Can you make clear optional?

### ISSUE THREAD

**Issue by koppi** [hzeller/timg#2]
Is it really necessary to clear the screen buffer before displaying the image? I want do do:
```bash
for f in $(ls *.png); do timg $f; done
```
and scroll back in the terminal, but in the current version of timg, before each image gets displayed, the terminal buffer gets cleared and only the last image is displayed in the terminal with the above command.

**Comment by hzeller** [comment]
I we only have one image (not animated gif or similar), then this would probably working fine; originally I had this for animations, so this is why I made a point in clearing, but that probably is not needed. Can you try how it looks if you don't do it ? Also there is a thing in the terminal-canvas that goes up height/2, which can be left out in that case as well.
If it looks good: can you prepare a pull request that does _not_ do the clear (unless request with an option, say -C) ?

**Comment by koppi** [comment]
Thank's @hzeller . This works very well. There's a typo in your last commit, see https://github.com/hzeller/timg/commit/21e58ea85c8be064d4d3822114fb4283f886cde1#diff-1238332770afc12459be31aa60d34bccR195
