### ISSUE TITLE
macOS install instructions

### ISSUE THREAD

**Issue by mooreniemi** [hzeller/timg#20]
I had success with these:

```bash
git clone https://github.com/hzeller/timg.git
cd timg/src
brew install GraphicsMagick webp # required libs.
make
make install
```

**Comment by m3at** [comment]
Confirmed these steps works on OSX 10.11.6.

When **using patched fonts** for non-ASCII text (iTerm 3.0.15 , Monaco for Powerline) it's painfully slow, crashing iTerm for bigger image sizes.
Other fixed width fonts works fine.
And for fun [Alacritty](https://github.com/jwilm/alacritty) is awesome with timg, ~0.2s to display a 3000x3000 picture.

**Comment by speedy-beaver** [comment]
Update, tested on macOS 11.2 on Apple Silicon

```
git clone https://github.com/hzeller/timg.git
cd timg/src
brew install GraphicsMagick webp ffmpeg # required libs now with video
export LDFLAGS="-L/opt/homebrew/lib" # homebrew default location on Apple Silicon for now
make
sudo make install
```

**Comment by hzeller** [comment]
Install instructions are now included in the toplevel README.
