### ISSUE TITLE
Fix signal handler

### ISSUE THREAD

**Issue by elfring** [hzeller/timg#21]
[The variable “`interrupt_received`”](https://github.com/hzeller/timg/blob/95708eaca47c4651545817fc5ccf3cc3346570b2/src/timg.cc#L39 "Update candidate") should [use the data type “`sig_atomic_t`”](https://www.securecoding.cert.org/confluence/display/c/SIG31-C.+Do+not+access+shared+objects+in+signal+handlers "Description around sig_atomic_t") (instead of “`bool`”).

**Comment by hzeller** [comment]
Thanks, fixed.

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/hzeller/timg/commit/218830b9ca56453a553e9c96a6abdf1d013076b2 "Use sig_atomic_t instead of bool").
