### ISSUE TITLE
Can't install in Oracle Linux

### ISSUE THREAD

**Issue by nspthegreat** [hzeller/timg#23]
did git and installing libwebp-dev and GraphicsMagick-c++-devel (libgraphicsmagick++-dev equivalent? https://pypi.python.org/pypi/pgmagick/)
with yum. 

But now when I type "make" i'm getting this error:

g++ -o timg timg.o terminal-canvas.o  -lGraphicsMagick++
/usr/bin/ld: timg.o: undefined reference to symbol 'CloneImageInfo'
/usr/lib64/libGraphicsMagick-Q16.so.3: error adding symbols: DSO missing from command line
collect2: Fehler: ld gab 1 als Ende-Status zurück
make: *** [timg] Fehler 1

What should I do now? :/

**Comment by hzeller** [comment]
so sounds like you need some library that provides CloneImageInfo. Currently, you only link the c++ wrapper, so you also need to link  `-lGraphicsMagick`

**Comment by nspthegreat** [comment]
I'm sorry I'm a noob. How do I do this? :)

**Comment by hzeller** [comment]
just add it it to the `MAGICK_LDFLAGS`

Or manually compile with
```
g++ -o timg timg.o terminal-canvas.o -lGraphicsMagick++ -lGraphicsMagick
```

**Comment by hzeller** [comment]
I guess you figured it out ?
