### ISSUE TITLE
How to put this forward for inclusion in Linux distros?

### ISSUE THREAD

**Issue by qume** [hzeller/timg#35]
I'm not familiar with how the process works to get software included in Linux distros, but little gem would be at the top of my list. It's small, portable and feels like a fundamental CLI tool to have on all systems.

I'd like to try but not sure where to start - a quick web search didn't help with that either. 

Anyone have any ideas?

**Comment by hzeller** [comment]
The documentation about packaging in the distributions might be a good start. For Debian, I found this https://wiki.debian.org/Packaging

Maybe there is a link how to suggest new package or find people who'd like to package it.

**Comment by hzeller** [comment]
Adding @coldtobi, who is involved with creating debian packages, might be able to help.

Tobias, this is a tool I wrote that at least one user would like to have packaged and at a few hundred others found at least :star:-worthy. Maybe you can give a few resources how to get packaging a new tool for Debian would get started ? Or maybe you'd like to take on yet another package ... :)

**Comment by coldtobi** [comment]
Thanks for the pointer… Yeah, maybe I could be talked into maintaining this package as well, its looks quite interesting.. 
(I'll put it on my todo list for now; Debian is about to freeze, so I need to do other things first to ensure the next stable release will be awesome)

As you asked for resources how to package for Debian: 
This link might be interesting as starting point how to maintain packages in Debian: https://mentors.debian.net/intro-maintainers/. * (Everyone can do that, no need to be Debian Developer (DD) for that. Just the upload needs to be sponsored by an DD.

To suggest new packages, one files a "RFP" (Request for Packaging) bug against the pseudo package wnpp (Work-Needing and Prospective Packages), best with the reportbug tool. ("reportbug wnpp"). But unfortunately the RFP list is long and there is no guarantee of any results; so if you really want to see it in Debian its best to get involved and step up and become a Debian Contributor and start maintaining the package.**

(*The link (intro-maintainer) might be a bit overwhelming, but learning curve on Debian packaging is quite steep, and the people at mentors.debian.net reviewing the packages are usually quite helpful as well. I'm around there too…) 

(** but be careful. They might suck in faster than you think;  like it happened the to me: Suddenly you find the Debian community so enjoyable that you get even more involved… It can happen than one day you wake up as DD… :smile: )

 </advertising>

**Comment by coldtobi** [comment]
https://bugs.debian.org/982087

**Comment by coldtobi** [comment]
Progress! https://salsa.debian.org/debian/timg

**Comment by coldtobi** [comment]
https://tracker.debian.org/news/1242700/accepted-timg-142-1-source-amd64-into-unstable-unstable/ :)
Soon installable with apt install timg  (when you follow Debian unstable)

**Comment by hzeller** [comment]
Yay. Thanks Tobi!

**Comment by qume** [comment]
Great work guys 

-- 
  Luke Reid
  ***@***.*** <mailto:luke%40reid.org.nz>

**Comment by hzeller** [comment]
I think we can close this now, as Debian, NixOS and MacOS brew are covered with readily-installable packages.
Redhat might be another distro someone should cover.
