### ISSUE TITLE
Image is blurry compared to icat

### ISSUE THREAD

**Issue by SolitudeSF** [hzeller/timg#45]
![image](https://user-images.githubusercontent.com/10168645/110220490-b6319e80-7ece-11eb-809e-67347623d401.png)

**Comment by hzeller** [comment]
`timg` is using `sws_scale()` in `SWS_BILINEAR` mode, which might be different from the scaling algorithm icat is using.
Usually bilinear scaling is usually considered pretty good overall quality, but different scaling algorithms might have different outcomes. Right now, this is not choosable via command line flag, maybe it should ? OTOH, I'd like to have it mostly 'work out of the box'.

(JPEG scaling code is [here](https://github.com/hzeller/timg/blob/main/src/jpeg-source.cc#L183-L187) if you want to play with it).

**Comment by SolitudeSF** [comment]
ah, i dont feel like downscaling should ever use bilinear, but that just my opinion.
