### ISSUE TITLE
Support `-p b` for using background colours and/or reverse video

### ISSUE THREAD

**Issue by Alhadis** [hzeller/timg#48]
For low-fidelity output, `\e[48;5;…m` or `\e[7;38;5;…m` is more likely to produce better-looking results than Unicode block characters. Here's how I'd do it:

~~~console
$ timg --pixelation=b 1px-solid-red.png | sed s/$'\e'/\\\\e/g
\e[7;38;2;255;0;0m \e[27;39m
~~~

Now, I know the readme says [this](https://github.com/hzeller/timg/blob/58b4ad7a8fce12d1f05339ff7616b1f31b862f03/README.md#half-block-and-quarter-block-rendering):

> Terminals that don't support Unicode or 24 bit color are not supported; they will probably not show a very pleasent output.

… so this rendering mode should emit 2 characters instead of 1 (possibly configurable with an option or environment variable):

<table width="800" align="center"><thead><tr align="center">
	<th width="25%" align="center">Actual image      <br/><sup>(4×5 @ 1700%)</sup>
	<th width="25%" align="center">Enlarged version  <br/><sup>(with pixel boundaries)</sup>
	<th width="25%" align="center">With 1 character  <br/><sup>Pixel ratio: 1.0</sup>
	<th width="25%" align="center">With 2 characters <br/><sup>Pixel ratio: 2.0</sup>
</tr></thead><tbody><tr>
	<td width="25%" align="center"><img src="https://user-images.githubusercontent.com/2346707/112616995-7f6cf980-8e78-11eb-8111-22f020bf8b24.png" alt="H (4×5px)" height="82" /></td>
	<td width="25%" align="center"><img src="https://user-images.githubusercontent.com/2346707/112617131-af1c0180-8e78-11eb-93de-bab365057a8d.png" alt="H (4×5px)" height="82" /></td>
	<td width="25%" align="center"><pre><code>█  █
█  █
████
█  █
█  █</code></pre></td>
	<td width="25%" align="center"><pre><code>██    ██
██    ██
████████
██    ██
██    ██</code></pre></td>
</tr></tbody></table>

The trade-off is that images take twice as much space to display, but that might be an acceptable compromise if users are happy with scrolling sideways to see the full image (by piping to `less -RS`), or if they know the image to be small enough to fit their terminal window.

**Comment by hzeller** [comment]
Not quite sure what your request is: would you like that upscaled images (e.g. using `-U`) are more 'sharp` ? Maybe we should introduce an 'upscale, but only in integer multiples' variant, so that in a scale of 2, a pixel either fits one half block, or 4 half blocks (= 2 spaces with background color set).

The `-U` is already there to not upscale (and 'unsharpify :)') images if they are very small (such as icons). But having an integer option to scale it as multiple of original pixels will then always produce a sharp output.

(For pixelation: Internally, timg already does optimize the case of two vertical same pixels being replaced by one space as background color. If the image was integer-scaled with factor two in each direction, we automatically get spaces with background color output)

**Comment by hzeller** [comment]
I've added now added an optional parameter to `--upscale`: 'i' for integer upscale.

So a small picture, like this sunflower without upscaling
```
timg tiny-sunflower.jpg
```
![sun-small](https://user-images.githubusercontent.com/140937/112684132-d13d6180-8e2f-11eb-9c7f-ad48e5ad0e6e.png)

... and that looks like this with `--upscale` (or `-U`) option (this looks bilinear scaling, so is 'fuzzy):
```
timg tiny-sunflower.jpg --upscale
```
![sun-upscale](https://user-images.githubusercontent.com/140937/112684247-f8942e80-8e2f-11eb-89bf-e6ad92b860e1.png)

... looks like this with integer upscaling `--upscale=i`:

```
timg tiny-sunflower.jpg --upscale=i
```
![sun-upscale-int](https://user-images.githubusercontent.com/140937/112684275-03e75a00-8e30-11eb-80d0-4e8ba40d6362.png)


Is this roughly what you had in mind ?

**Comment by Alhadis** [comment]
Wait, I forgot that `Terminal.app` doesn't support 24-bit colours. I blindly assumed the following mess to be the fault of my terminal font:

<img src="https://user-images.githubusercontent.com/2346707/112692007-52e5cb80-8ed2-11eb-9f4d-9799d62e2acf.png" alt="Terminal.app" width="500" />

However, Alacritty proved that wasn't the case:

<img src="https://user-images.githubusercontent.com/2346707/112692244-b8d25300-8ed2-11eb-86e8-0cda2ad3660e.png" alt="Alacritty" width="500" />

I filed this issue before I remembered `\e[35;2;R;G;Bm` gets mangled by `Terminal.app`, so... 😅

On that note, is there a way to force `\e[35;5;…m` escapes for terminals that don't support 24-bit colour?

**Comment by hzeller** [comment]
> On that note, is there a way to force \e[35;5;…m escapes for terminals that don't support 24-bit colour?

Not right now. It is the question if it is worthwhile supporting the by now mere handful of ancient terminals that do not support 24 bit color (without decreasing code readability too much or performance) vs. filing bugs with them to actually support it.

I mean, even xterm supports 24 bit color these days. And that is an ancient application from 1984 but still up to the present time.

Please file a bug for 256 color support. Let's see if that is more requested (and potentially considering sending a pull-request).

**Comment by hzeller** [comment]
Just tested 256 color support. Probably not too involved to add.

To test, please check out `color-256-testing` branch:
https://github.com/hzeller/timg/tree/color-256-testing

**Comment by hzeller** [comment]
Alright, there is now a `--color8` option :)

**Comment by hzeller** [comment]
I guess we can close this one ?

**Comment by Alhadis** [comment]
Jesus. That was quick.

Thanks for the fast response!
