### ISSUE TITLE
How to detect next frame in the output stream to stdout

### ISSUE THREAD

**Issue by Moelf** [hzeller/timg#59]
Amazing package, Kitty's raw API isn't great for positioning etc so I really appreciate this. I'm trying to use `timg` inside a mother language's REPL, currently, I'm running `timg` directly which would take over the stdout, but I also want to have control in case I need to redirect it.

My question is when I'm reading the stdout of `timg`, is there a separator I can look for so I know to print frame by frame?

**Comment by hzeller** [comment]
There is an uppercase A in the output after a square-bracket and a number `[<somenumber>A`. This is the escape code that jumps the cursor back up after a frame is finished, and you could use that to detect frame separation.

In the [README](https://github.com/hzeller/timg/blob/main/README.md), there is an example how to use that to replay an animation with time-delay using awk; search for `xzcat` on that page.
