### ISSUE TITLE
Make error: "use of undeclared identifier 'clock_nanosleep'"

### ISSUE THREAD

**Issue by anoduck** [hzeller/timg#63]
Received the following error attempting to compile the app in OpenBSD Current (7.0).

```shell
 use of undeclared identifier 'clock_nanosleep'
        clock_nanosleep(CLOCK_MONOTONIC, TIMER_ABSTIME, &time_, nullptr);
```

I imagine this might have something to do with OpenBSD's use of clang and the absence of GCC from the system.

**Comment by hzeller** [comment]
(leaving open until confirmed working)

**Comment by anoduck** [comment]
It worked like butter! Smooth as silk. Thanks!
