### ISSUE TITLE
EXIF Rotation not working

### ISSUE THREAD

**Issue by xeruf** [hzeller/timg#65]
Exiftool says:

    Orientation                     : Rotate 270 CW

Exif says:

    Orientation         |Left-bottom

In graphical programs the image is turned correctly, but `timg --rotate=exif` does not turn it :/

**Comment by hzeller** [comment]
Can you share the image somewhere?  Locating the exif data maybe is too simple in timg to find it in your image, so we need to see how it is there.

**Comment by hzeller** [comment]
I need your particular image that is not working as it is usually working fine for all the exif rotated files I tested so far.

**Comment by xeruf** [comment]
It works, I dunno what went wrong there ;)

**Comment by xeruf** [comment]
Found the issue: I am passing `-V` as workaround to https://github.com/hzeller/timg/issues/68 which disables EXIF detection :c
