### ISSUE TITLE
I can't compile on termux

### ISSUE THREAD

**Issue by bropines** [hzeller/timg#74]
[ 93%] Building CXX object src/CMakeFiles/timg.dir/video-display.cc.o
/data/data/com.termux/files/home/timg/src/video-display.cc:163:20: error: assigning to 'AVCodec *' from 'const AVCodec *' discards qualifiers
        av_codec = avcodec_find_decoder(codec_parameters->codec_id);
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [src/CMakeFiles/timg.dir/build.make:272: src/CMakeFiles/timg.dir/video-display.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:116: src/CMakeFiles/timg.dir/all] Error 2
make: *** [Makefile:156: all] Error 2

**Comment by bropines** [comment]
At the same time, the previously working codec via ffmpeg does not work.

**Comment by hzeller** [comment]
Can you do a `git pull` and try to compile again ?
I suspect a change in the API is a bit more tight in returning a const pointer.

**Comment by bropines** [comment]
Yes, the compilation is successful. Everything works
