### ISSUE TITLE
Compile error with ffmpeg 5

### ISSUE THREAD

**Issue by wilriker** [hzeller/timg#78]
Compiling with ffmpeg 5.x results in
```
timg-1.4.3/src/video-display.cc: In member function ‘virtual bool timg::VideoLoader::LoadAndScale(const timg::DisplayOptions&, int, int)’:
timg-1.4.3/src/video-display.cc:163:40: error: invalid conversion from ‘const AVCodec*’ to ‘AVCodec*’ [-fpermissive]
  163 |         av_codec = avcodec_find_decoder(codec_parameters->codec_id);
      |                    ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                        |
      |                                        const AVCodec*
```

**Comment by hzeller** [comment]
I [recently changed](https://644db4de3505c40a0444-327723bce298e3ff5813fb42baeefbaa.ssl.cf1.rackcdn.com/c7cf036b5b5552df84b0d83c03a28e8a.png) this to be const, Did you build from head or the slightly before 1.4.3 release ?

**Comment by hzeller** [comment]
(Also see #74)

**Comment by wilriker** [comment]
It was built with 1.4.3. Release. This has been released on 2022-01-08 and the change you mentioned only was on 2022-02-06 so this cannot be part of that release.

So I am waiting for a new release.

(BTW: I am the maintainer of the AUR package and get notified about new releases so I can update the package).

**Comment by hzeller** [comment]
Created new release 1.4.4 that contains the latest changes https://github.com/hzeller/timg/releases/tag/v1.4.4

**Comment by wilriker** [comment]
Thanks! I can confirm it's working again. :+1:
