### ISSUE TITLE
On beta versions of termux such bug

### ISSUE THREAD

**Issue by bropines** [hzeller/timg#91]
![Screenshot_2022-10-07-02-32-00-066_com termux](https://user-images.githubusercontent.com/57861007/194422688-4743a6cb-a078-4eee-934c-c80d82a9783b.jpg)

**Comment by hzeller** [comment]
You probably need to report that who is packaging `timg` for `termux`: this looks like a linking issue with the underlying graphics library.

If you compile it yourself, maybe switch off the `WITH_GRAPHICSMAGICK` option to cmake. Then the fallback code will also be able to open the png image.

**Comment by bropines** [comment]
It seems that support was not removed by commits, but for some reason it outputs like this.
![Screenshot_2022-10-18-03-02-16-870_com termux](https://user-images.githubusercontent.com/57861007/196293468-0300a351-6009-4392-95c5-01dac797d3a2.jpg)

**Comment by rihaq** [comment]
@hzeller I can view image but why video not playing using iterm2 protocol? 😡
`Terminal does not support pixel size query, but graphics protocol requested.
Can't show animations or have columns in grid.`

**Comment by hzeller** [comment]
`timg` can't determine the size of the textcell because `termux` needs to implement `TIOCGWINSZ` with ws_xpixel and ws_ypixel set. Without that, timg does not have enough information to show animations or videos.

Please file a feature request with termux to have it implemented @rihaq

**Comment by aicynide** [comment]
Use termux-monet and close this issue
