### ISSUE TITLE
Feature request: support sixel format

### ISSUE THREAD

**Issue by data-man** [hzeller/timg#96]
Many terminals supports [sixel](https://en.wikipedia.org/wiki/Sixel) only.

Proposals:
* migrate to ImageMagick (which supports sixels out-from-the-box) or
* use [libsixel](https://github.com/libsixel/libsixel)

**Comment by hzeller** [comment]
Added in https://github.com/hzeller/timg/commit/572c76339970bca41c273b65cce57b1b379c521d

Still needs some final tests, but looks pretty promising. Can be chosen with `-psixel`

**Comment by hzeller** [comment]
Finished tests. Seems to work with the various terminals I tested (including needed worarounds)

 * xterm -ti vt340
 * mlterm
 * konsole (though by default timg will use `-p iterm` there)
 * xfce4-terminal (compiled with latest `vte` that allows for sixels)
 * wezterm
 * [alacritty-sixel](https://github.com/microo8/alacritty-sixel)

Will be in a release shortly.
